# Generated by Django 6.0.6 on 2026-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('quantity_per_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('units_in_stock', models.SmallIntegerField(blank=True, null=True)),
                ('units_on_order', models.SmallIntegerField(blank=True, null=True)),
                ('reorder_level', models.SmallIntegerField(blank=True, null=True)),
                ('discontinued', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
