# Generated by Django 6.0.6 on 2026-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('shipper_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'shippers',
                'managed': False,
            },
        ),
    ]
