# Generated by Django 6.0.6 on 2026-06-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
    ]
