# Generated by Django 6.0.6 on 2026-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('title_of_courtesy', models.CharField(blank=True, max_length=25, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=24, null=True)),
                ('extension', models.CharField(blank=True, max_length=4, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTerritories',
            fields=[
                ('pk', models.CompositePrimaryKey('employee_id', 'territory_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employee_territories',
                'managed': False,
            },
        ),
    ]
