# Generated by Django 6.0.6 on 2026-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsStates',
            fields=[
                ('state_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state_abbr', models.CharField(blank=True, max_length=2, null=True)),
                ('state_region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'us_states',
                'managed': False,
            },
        ),
    ]
