# Generated by Django 6.0.6 on 2026-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('region_description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('territory_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('territory_description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'territories',
                'managed': False,
            },
        ),
    ]
